version: "3.8"

services:
  redis:
    image: redis:7.0.11
    ports:
      - "6379:6379"
  # A MySQL database for development.
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: chirp
    ports:
      - "3306:3306"
