version: "3.8"

services:
  # A MySQL database for development.
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: chirp
    ports:
      - "3306:3306"
